
    create table tasks (
        is_repeated boolean,
        created_at timestamp(6),
        delete_date_time timestamp(6),
        end_date_time timestamp(6),
        image_id bigint generated by default as identity,
        start_date_time timestamp(6),
        task_id bigint,
        task_priority INTEGER CHECK (task_priority >= 1 AND task_priority <=3) check ((task_priority<=3) and (task_priority>=1)),
        updated_at timestamp(6),
        user_id bigint,
        image TEXT not null,
        task_description varchar(255),
        task_title varchar(255) not null,
        primary key (task_id)
    );

    create table users (
        birth_date date,
        is_active boolean,
        created_at timestamp(6),
        deleted_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint generated by default as identity,
        code_fiscale varchar(16) not null,
        email varchar(255) not null unique,
        name varchar(255) not null,
        profile_image varchar(255),
        surname varchar(255) not null,
        primary key (user_id)
    );

    alter table if exists tasks 
       add constraint FKocg5h7sg0hfg92cfutkbvow4g 
       foreign key (task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FK6s1ob9k4ihi75xbxe2w0ylsdh 
       foreign key (user_id) 
       references users;
